stages:
  - build
  - test
  - deploy

include:
  - local: ".gitlab/ci/base.yml"
  - local: ".gitlab/ci/docker-images.yml"
  - local: ".gitlab/ci/merge-request.yml"
  - local: ".gitlab/ci/pages.yml"
#  - local: ".gitlab/ci/publish-snapshots.yml" # disabled until fixed
