stages:
  - build
  - test
  - deploy

include:
  - local: ".gitlab/base.yml"
  - local: ".gitlab/merge-request.yml"
  - local: ".gitlab/pages.yml"
#  - local: ".gitlab/publish-snapshots.yml" # disabled until fixed
