# Sharing dependency versions between projects
# https://docs.gradle.org/current/userguide/platforms.html

[versions]
detekt = "1.22.0"
gradle = "7.6"
kotlin = "1.8.10"
xmlutil = "0.84.3"

[libraries]
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version = "5.8.2" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version = "1.12.0" }
kotlinx-cli = { module = "org.jetbrains.kotlinx:kotlinx-cli", version = "0.3.5" }
kxml2 = { module = "net.sf.kxml:kxml2", version = "2.3.0" }
xmlutil-core = { module = "io.github.pdvrieze.xmlutil:core", version.ref = "xmlutil" }
xmlutil-serialization = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xmlutil" }


# plugins
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
xmlutil = ["xmlutil-core", "xmlutil-serialization"]

[plugins]
gradledoctor = { id = "com.osacky.doctor", version = "0.8.1" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
