# Sharing dependency versions between projects
# https://docs.gradle.org/current/userguide/platforms.html

[versions]
java = "17"
detekt = "1.22.0"
gradle = "8.1.1"
kotlin = "1.8.21"
dokka = "1.8.10"
kotlin-logging = "4.0.0-beta-28"
ktlint = "0.49.0"
log4j = "2.20.0"
prettier = "2.4.1"
xmlutil = "0.84.3"

[libraries]
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
kotlin-logging-linux-arm64 = { module = "io.github.oshai:kotlin-logging-mingwx64", version.ref = "kotlin-logging" }
kotlin-logging-linux-x64 = { module = "io.github.oshai:kotlin-logging-linuxx64", version.ref = "kotlin-logging" }
kotlin-logging-macos-arm64 = { module = "io.github.oshai:kotlin-logging-mingwx64", version.ref = "kotlin-logging" }
kotlin-logging-macos-x64 = { module = "io.github.oshai:kotlin-logging-mingwx64", version.ref = "kotlin-logging" }
kotlin-logging-mingw-x64 = { module = "io.github.oshai:kotlin-logging-mingwx64", version.ref = "kotlin-logging" }
kotlin-test-annotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version = "1.13.1" }
kotlinx-cli = { module = "org.jetbrains.kotlinx:kotlinx-cli", version = "0.3.5" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.5.0" }
ktlint-cli-ruleset-core = { module = "com.pinterest.ktlint:ktlint-cli-ruleset-core", version.ref = "ktlint" }
ktlint-core = { module = "com.pinterest.ktlint:ktlint-core", version.ref = "ktlint" }
ktlint-rule-engine = { module = "com.pinterest.ktlint:ktlint-rule-engine", version.ref = "ktlint" }
ktlint-ruleset-experimental = { module = "com.pinterest.ktlint:ktlint-ruleset-experimental", version.ref = "ktlint" }
ktlint-ruleset-standard = { module = "com.pinterest.ktlint:ktlint-ruleset-standard", version.ref = "ktlint" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }

# plugins
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "6.17.0" }
plugin-versionsgradle = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.45.0" }

[bundles]
kotlin-logging-jvm = ["kotlin-logging-jvm", "log4j-api", "log4j-core", "log4j-slf4j2-impl"]
ktlint = ["ktlint-core", "ktlint-cli-ruleset-core", "ktlint-rule-engine", "ktlint-ruleset-standard"]

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradledoctor = { id = "com.osacky.doctor", version = "0.8.1" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.24.0" }
gradlePluginPublish = { id = "com.gradle.plugin-publish", version = "0.21.0" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "3.1.0" }
