name: Linux CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: set up Gnome Dev
        run: |
          set -e -v

          sudo apt-get update

          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            apt-utils \
            openjdk-17-jdk-headless \
            python3-pip \
            gcc-multilib \
            libgirepository1.0-dev \
            libadwaita-1-dev \
            libgtksourceview-5-dev \
            libwebkitgtk-6.0-dev

          sudo apt-get clean

      - name: set up CI
        run: |
          GRADLE_USER_HOME="$(pwd)/.gradle"
          export GRADLE_USER_HOME
          mkdir -p $GRADLE_USER_HOME ; cp .ci/ci-gradle.properties $GRADLE_USER_HOME/gradle.properties

      - name: Build with Gradle
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          ./gradlew :gir:run
          ./gradlew assemble
          ./gradlew gradle-plugin:publishAllPublicationsToSnapshotsRepository
          ./gradlew publishAllPublicationsToSnapshotsRepository
